### PR TITLE
Added my details

### PR DESCRIPTION
**Pull request by SamChus**

### CODE REVIEW

**Comment by lumenCodes** [comment]
Hi Samuel,

Thanks for this PR, just a little feedback on it.

- The PR title should be descriptive or if it is not descriptive, you can add a description in the body.

We will merge this soonest.

**Comment by SamChus** [comment]
> Hi Samuel,
> 
> Thanks for this PR, just a little feedback on it.
> 
> * The PR title should be descriptive or if it is not descriptive, you can add a description in the body.
> 
> We will merge this soonest.

Ok ma, Thanks.

**Comment by thekingslee** [comment]
Good job @SamChus, here's a good resource to help you improve your commit messages
https://chiamakaikeanyi.dev/how-to-write-good-git-commit-messages/

**Comment by thekingslee** [comment]
Congratulations! you just made your first contribution

**Comment by SamChus** [comment]
Thank you sir
Pls can I have you WhatsApp number...pls

**Pull request merged**
